// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace blog_backend.Models
{
    public partial class Categories
    {
        public Categories()
        {
            Post = new HashSet<Post>();
        }

        public string CategoryId { get; set; }
        public string CategoryName { get; set; }

        public virtual ICollection<Post> Post { get; set; }
    }
}