// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace blog_backend.Models
{
    public partial class Post
    {
        public Post()
        {
            Comment = new HashSet<Comment>();
        }

        public string IdPost { get; set; }
        public string Title { get; set; }
        public string ContentPost { get; set; }
        public string IdUser { get; set; }
        public string CategoryId { get; set; }
        public byte[] CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public string UrlPost { get; set; }
        public bool? Status { get; set; }

        public virtual Categories Category { get; set; }
        public virtual AspNetUsers IdUserNavigation { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
    }
}